# 'Temporary' script to set up an acquisition node

dbpf "$(P)$(NODE):ACQ:coupling:01" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:02" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:03" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:04" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:05" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:06" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:07" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:08" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:09" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:10" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:11" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:12" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:13" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:14" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:15" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:16" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:17" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:18" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:19" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:20" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:21" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:22" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:23" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:24" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:25" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:26" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:27" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:28" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:29" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:30" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:31" "DC"
dbpf "$(P)$(NODE):ACQ:coupling:32" "DC"

dbpf "$(P)$(NODE):ACQ:enable:01" 1
dbpf "$(P)$(NODE):ACQ:enable:02" 1
dbpf "$(P)$(NODE):ACQ:enable:03" 1
dbpf "$(P)$(NODE):ACQ:enable:04" 1
dbpf "$(P)$(NODE):ACQ:enable:05" 1
dbpf "$(P)$(NODE):ACQ:enable:06" 1
dbpf "$(P)$(NODE):ACQ:enable:07" 1
dbpf "$(P)$(NODE):ACQ:enable:08" 1
dbpf "$(P)$(NODE):ACQ:enable:09" 1
dbpf "$(P)$(NODE):ACQ:enable:10" 1
dbpf "$(P)$(NODE):ACQ:enable:11" 1
dbpf "$(P)$(NODE):ACQ:enable:12" 1
dbpf "$(P)$(NODE):ACQ:enable:13" 1
dbpf "$(P)$(NODE):ACQ:enable:14" 1
dbpf "$(P)$(NODE):ACQ:enable:15" 1
dbpf "$(P)$(NODE):ACQ:enable:16" 1
dbpf "$(P)$(NODE):ACQ:enable:17" 1
dbpf "$(P)$(NODE):ACQ:enable:18" 1
dbpf "$(P)$(NODE):ACQ:enable:19" 1
dbpf "$(P)$(NODE):ACQ:enable:20" 1
dbpf "$(P)$(NODE):ACQ:enable:21" 1
dbpf "$(P)$(NODE):ACQ:enable:22" 1
dbpf "$(P)$(NODE):ACQ:enable:23" 1
dbpf "$(P)$(NODE):ACQ:enable:24" 1
dbpf "$(P)$(NODE):ACQ:enable:25" 1
dbpf "$(P)$(NODE):ACQ:enable:26" 1
dbpf "$(P)$(NODE):ACQ:enable:27" 1
dbpf "$(P)$(NODE):ACQ:enable:28" 1
dbpf "$(P)$(NODE):ACQ:enable:29" 1
dbpf "$(P)$(NODE):ACQ:enable:30" 1
dbpf "$(P)$(NODE):ACQ:enable:31" 1
dbpf "$(P)$(NODE):ACQ:enable:32" 1

